-- MySQL Script generated by MySQL Workbench
-- Mon May 30 20:45:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`),
  UNIQUE INDEX `cod_pessoa_UNIQUE` (`cod_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `nome_animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`),
  UNIQUE INDEX `animal_UNIQUE` (`nome_animal` ASC) VISIBLE,
  UNIQUE INDEX `cod_animal_estimacao_UNIQUE` (`cod_animal_estimacao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `nome_bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`),
  UNIQUE INDEX `bebida_UNIQUE` (`nome_bebida` ASC) VISIBLE,
  UNIQUE INDEX `cod_bebida_UNIQUE` (`cod_bebida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `nome_clima` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clima`),
  UNIQUE INDEX `clima_UNIQUE` (`nome_clima` ASC) VISIBLE,
  UNIQUE INDEX `cod_clima_UNIQUE` (`cod_clima` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hobbie` (
  `cod_hobbie` INT NOT NULL AUTO_INCREMENT,
  `nome_hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`),
  UNIQUE INDEX `hobbie_UNIQUE` (`nome_hobbie` ASC) VISIBLE,
  UNIQUE INDEX `cod_hobbie_UNIQUE` (`cod_hobbie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coleta` (
  `cod_coleta` INT NOT NULL,
  `data_coleta` DATE NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  `cod_hobbie` INT NOT NULL,
  `cod_pessoa` INT NOT NULL,
  PRIMARY KEY (`cod_coleta`),
  INDEX `fk_coleta_animal_estimacao_idx` (`cod_animal_estimacao` ASC) VISIBLE,
  INDEX `fk_coleta_bebida1_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_coleta_clima1_idx` (`cod_clima` ASC) VISIBLE,
  INDEX `fk_coleta_hobbie1_idx` (`cod_hobbie` ASC) VISIBLE,
  INDEX `fk_coleta_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_coleta_animal_estimacao`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `mydb`.`animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `mydb`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `mydb`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `mydb`.`hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleta_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `mydb`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
